services:
  - type: web
    name: hisab-kitab-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m hisab_kitab_bot.bot
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        value: Hisab_Kitab_1Bot
      - key: PYTHON_VERSION
        value: 3.10.12
